### ISSUE TITLE
Add db backup shortcut

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/ov-deploy#43]
### Because

As a developer
I can run a single command to download a postgres dump to my local machine
because I need a quick and reliable way to do database backups.

### Done when

- [x] command downloads pgdump to local machine

**Comment by mrharpo** [comment]
# Command
Needed this today.

```shell
kubectl exec -it [DB_POD_NAME] -- /usr/local/bin/pg_dump -Fc -U postgres postgres
```

This outputs the dump file to the console. Adding `> $FILENAME.sql` outputs to a local file.

**Comment by mrharpo** [comment]
# Date
Bonus points for including the date in the one-liner:
```shell
kubectl exec -it [DB_POD_NAME] -- /usr/local/bin/pg_dump -Fc -U postgres postgres > db_$(date +%Y-%m-%d_%H-%M-%S).sql
```

This generates the file `db_2022-10-04_13-43-43.sql`

**Comment by mrharpo** [comment]
# get pod name
After some extensive searching , I found an easy and reliable `kubectl` oneliner to get the list of pods for a workload (without relying on `| grep [NAME]`):
```bash
kubectl get pods -l workload.user.cattle.io/workloadselector="deployment-openvault-db" -o name
```
Returns:
```bash
pod/db-7bc8699d94-nh8gh
```

**Comment by mrharpo** [comment]
Closing, because we are going with an RDS database, which has built in backup / restore functionality.

Can reopen if we want to run backup / restore from a CLI.
