### ISSUE TITLE
Add db restore shortcut

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/ov-deploy#44]
### Because

As a developer
I can run a single command to restore the database from a local postgres dump file
by specifying the arguments:
* path to the pg dump file
* which kube context i want to use (which corresponds to Demo or Production namespace)
because I need db restorations to be simple, fast, and reliable.

### Done when

- [x] There is a single command with minimal arguments that restores the database to either Prod or Demo namespaces.

**Comment by mrharpo** [comment]
WIth #43,

# Command
### **This is untested!** 
But it should be:
```shell
kubectl exec -it [DB_POD_NAME] -- /usr/local/bin/pg_restore --verbose --clean --no-acl --no-owner -U postgres -d postgres < $FILENAME
```

**Comment by mrharpo** [comment]
Closing, because we are going with an RDS database, which has built in backup / restore functionality.

Can reopen if we want to run backup / restore from a CLI.
